### ISSUE TITLE
change database

### ISSUE THREAD

**Issue by fanleesss** [Alfresco/acs-community-deployment#113]
hello everyone!How can i change the database ,from postgres change to mysql。How can I do?Please help me!

**Comment by JoniSanchez** [comment]
Hello!
The project has not implemented that change as far as I can see. You have two options:
The first is to take Helm and add the Mysql chart to the Alfresco chart to contribute to the project, or the quick option with Helm from Mysql to deploy separately, and connect Alfresco to an external database and change the data to MySQL.

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

You will need to add the MySQL driver to the repository docker image by building a custom image and then update the properties passed to the repository to point to your MySQL database instead of Postgres. How to do this will depend on whether you're using docker compose or Helm.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

The new consolidated repository https://github.com/Alfresco/acs-deployment has more documentation and examples that may be of use, in particular these two: https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/examples/with-aws-services.md (how to use an external database) and https://github.com/Alfresco/acs-deployment/blob/master/docs/docker-compose/examples/customisation-guidelines.md
